<Project Sdk="Aspire.AppHost.Sdk/13.4.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>c9027c8c-098d-4c1c-963d-73185c213632</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="Aspire.Hosting.SqlServer" Version="*" />
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.4.3" />
    <PackageReference Include="Aspire.Hosting.NodeJs" Version="9.5.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AuthorizationAPI\AuthorizationAPI.csproj" />
    <ProjectReference Include="..\Frontend\BFF.FrontendProxy\BFF.FrontendProxy.csproj" />
    <ProjectReference Include="..\ProfilesAPI\ProfilesAPI.csproj" />
  </ItemGroup>

</Project>
