<Project Sdk="Aspire.AppHost.Sdk/13.4.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>c9027c8c-098d-4c1c-963d-73185c213632</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Redis" Version="*" />
	<PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.4.6" />
	<PackageReference Include="Aspire.Hosting.SqlServer" Version="*" />
    <PackageReference Include="Aspire.Hosting.JavaScript" Version="13.4.3" />
    <PackageReference Include="Aspire.Hosting.NodeJs" Version="9.5.2" />
    <PackageReference Include="Aspire.Hosting.MongoDB" Version="*" />
    <PackageReference Include="Aspire.Hosting.RabbitMQ" Version="*" />
    <PackageReference Include="Aspire.Hosting.Azure.Storage" Version="*" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Backend\AppointmentsAPI\AppointmentsAPI.csproj" />
    <ProjectReference Include="..\Backend\Deunde.IdentityServer\Deunde.IdentityServer.csproj" />
    <ProjectReference Include="..\Backend\DocumentsAPI\DocumentsAPI.csproj" />
    <ProjectReference Include="..\Backend\NotificationService.Worker\NotificationService.Worker.csproj" />
    <ProjectReference Include="..\Backend\OfficesApi\OfficesApi.csproj" />
    <ProjectReference Include="..\Backend\ProfilesAPI\ProfilesAPI.csproj" />
    <ProjectReference Include="..\Backend\ServicesAPI\ServicesAPI.csproj" />
    <ProjectReference Include="..\Frontend\BFF.FrontendProxy\BFF.FrontendProxy.csproj" />
  </ItemGroup>

</Project>
