# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Restore dependencies
        run: dotnet restore AuthorizationAPI.sln

      - name: Build
        run: dotnet build AuthorizationAPI.sln --no-restore

      - name: Test
        run: dotnet test AuthorizationAPI.sln --no-build --verbosity normal

      - name: Install hsim CLI Tool
        run: dotnet tool install --global DiNet.HashSimilarityTK.Cli --version 0.0.2
      
      - name: Run hsim to Gather Metrics
        run: hsim ./ \
          --numHashes 128 \
          --chunkStep 32 \
          --shingleSize 16 \
          --top 5
          --ignore "./hsim.ignore
